akreditasi/modules/kriteria9/modules/prodi/controllers/ProfilController.php
<?php
/**
 * Project: kriteria.
 * @author Adryan Eka Vandra <adryanekavandra@gmail.com>
 *
 * Date: 11/7/2019
 * Time: 11:32 AM
 */

namespace akreditasi\modules\kriteria9\modules\prodi\controllers;

use akreditasi\models\kriteria9\forms\StrukturOrganisasiUploadForm;
use akreditasi\modules\kriteria9\controllers\BaseController;
use common\models\FakultasAkademi;
use common\models\Profil;
use common\models\ProgramStudi;
use Yii;
use yii\base\Exception;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

class ProfilController extends BaseController
{

    public function behaviors()
    {
        return[
            'verbs'=>[
                'class'=>'yii\filters\VerbFilter',
                'actions' => [
                    'hapus-struktur'=>['POST']
                ]
            ]
        ];
    }

    public function actionIndex($prodi)
    {
        $programstudi = ProgramStudi::findOne($prodi);

        return $this->render('index', ['programstudi'=>$programstudi]);
    }
    public function actionUpdate($prodi)
    {
        $model = ProgramStudi::findOne($prodi);
        $dataFakultas = ArrayHelper::map(FakultasAkademi::find()->all(), 'id', 'nama');
        $jenjang = ProgramStudi::JENJANG;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Berhasil mengubah ProgramStudi.');

            return $this->redirect(['default/index', 'prodi' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'dataFakultas' => $dataFakultas,
            'jenjang'=>$jenjang
        ]);
    }

    public function actionUpdateProfil($prodi)
    {
        $model = ProgramStudi::findOne($prodi);
        /** @var Profil $profil */
        $profil = $model->profil;
        $strukturModel = new StrukturOrganisasiUploadForm();

        if ($profil->load(Yii::$app->request->post()) && $strukturModel->load(Yii::$app->request->post())) {
            $strukturModel->struktur = UploadedFile::getInstance($strukturModel, 'struktur');
            if (isset($strukturModel->struktur)) {
                $save = $strukturModel->upload($profil->type, $model->id);
                if (!$save) {
                    throw new \Exception('Error upload data');
                }
                $profil->struktur_organisasi = $save;
            }

            if (!$profil->save(false)) {
                throw new Exception('Gagal mengupdate profil');
            }
            Yii::$app->session->setFlash('success', 'Berhasil mengupdate profil');
            return $this->redirect(['profil/index','prodi'=>$model->id]);
        }

        return $this->render('update-profil', compact('model', 'profil', 'strukturModel'));
    }

    public function actionHapusStruktur()
    {

        $nama = Yii::$app->request->post('nama');
        $id = Yii::$app->request->post('id');

        $prodi = ProgramStudi::findOne($id);
        $profil = $prodi->profil;
        FileHelper::unlink(Yii::getAlias("@uploadStruktur/{$profil->type}/$id/$nama"));
        $profil->struktur_organisasi = '';


        return $profil->save(false);
    }
}

akreditasi/modules/kriteria9/modules/prodi/views/profil/_form-profil.php
<?php

use common\models\Constants;
use dmstr\ajaxbutton\AjaxButton;
use dosamigos\tinymce\TinyMce;
use kartik\file\FileInput;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model common\models\ProgramStudi */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $profil common\models\Profil */
/* @var $strukturModel akreditasi\models\kriteria9\forms\StrukturOrganisasiUploadForm */
?>


<div class="profil-program-studi-form">

    <?php $form = ActiveForm::begin(['id' => 'profil-prodi-form']); ?>

    <?= $form->field($profil, 'visi')->widget(TinyMce::class, [
        'options' => ['rows' => 6],

        'language' => 'id',
        'clientOptions' => [

            'plugins' => [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak placeholder',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc noneditable',
            ],
            'toolbar' => 'undo redo| styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | ltr rtl | link'

        ]
    ]) ?>


    <?= $form->field($profil, 'misi')->widget(TinyMce::class, [
        'options' => ['rows' => 6],

        'language' => 'id',
        'clientOptions' => [

            'plugins' => [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak placeholder',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc noneditable',
            ],
            'toolbar' => 'undo redo| styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | ltr rtl | link'

        ]
    ]) ?>
    <?= $form->field($profil, 'tujuan')->widget(TinyMce::class, [
        'options' => ['rows' => 6],

        'language' => 'id',
        'clientOptions' => [

            'plugins' => [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak placeholder',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc noneditable',
            ],
            'toolbar' => 'undo redo| styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | ltr rtl | link'

        ]
    ]) ?>
    <?= $form->field($profil, 'sasaran')->widget(TinyMce::class, [
        'options' => ['rows' => 6],

        'language' => 'id',
        'clientOptions' => [

            'plugins' => [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak placeholder',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc noneditable',
            ],
            'toolbar' => 'undo redo| styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | ltr rtl | link'

        ]
    ]) ?>
    <?= $form->field($profil, 'motto')->widget(TinyMce::class, [
        'options' => ['rows' => 6],

        'language' => 'id',
        'clientOptions' => [

            'plugins' => [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak placeholder',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc noneditable',
            ],
            'toolbar' => 'undo redo| styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | ltr rtl | link'

        ]
    ]) ?>
    <?= $form->field($profil, 'sambutan')->widget(TinyMce::class, [
        'options' => ['rows' => 6],

        'language' => 'id',
        'clientOptions' => [

            'plugins' => [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak placeholder',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc noneditable',
            ],
            'toolbar' => 'undo redo| styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | ltr rtl | link'

        ]
    ]) ?>
    <?php if ($profil->struktur_organisasi):?>
        <div id="current-struktur">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th>Berkas Struktur Organisasi Saat ini</th>
                    <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><?=Html::img(Yii::getAlias("@.uploadStruktur/{$profil->type}/{$model->id}/{$profil->struktur_organisasi}"), ['width'=>'50%'])?></td>
                    <td>
                        <?= AjaxButton::widget([
                                'id' => 'hapus-struktur-button',
                            'url' => ['profil/hapus-struktur'],
                            'method' => 'POST',
                            'content' => Yii::t('app', 'Hapus'),
                            'options' => ['class'=>'btn btn-danger btn-elevate btn-elevate-air'],
                            'params' => ['nama'=>$profil->struktur_organisasi,'id'=>$profil->external_id],
                            'successExpression' => new JsExpression('function(resp,status,xhr){
                            if(resp){
                                const elem = document.getElementById("current-struktur");
                                elem.parentNode.removeChild(elem);
                            }

                            }')
                        ])?>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

    <?php endif; ?>
    <?= $form->field($strukturModel, 'struktur')->widget(FileInput::class, [

        'pluginOptions' => [
            'theme' => 'explorer-fas',
            'maxFileSize' => Constants::MAX_UPLOAD_SIZE(),
            'allowedFileExtensions' => Constants::IMAGE_EXTENSIONS,
            'showUpload' => false,
            'previewFileType' => 'any',
            'fileActionSettings' => [
                'showZoom' => true,
                'showRemove' => false,
                'showUpload' => false,
            ],
        ]
    ]) ?>


    <div class="form-group">
        <?= Html::submitButton('<i class=\'la la-save\'></i> Simpan', ['class' => 'btn btn-pill btn-elevate btn-elevate-air btn-brand block-ui']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<?php
$jsForm = <<<JS
 $('form').on('beforeSubmit', function()
    {
        var form = $(this);
        //console.log('before submit');

        var submit = form.find(':submit');
        KTApp.block('.modal',{
            overlayColor: '#000000',
            type: 'v2',
            state: 'primary',
            message: 'Sedang Memproses...'
        });
        submit.html('<i class="flaticon2-refresh"></i> Sedang Memproses');
        submit.prop('disabled', true);

    });

JS;

$this->registerJs($jsForm);
?>

akreditasi/modules/kriteria9/modules/prodi/views/profil/_form.php
<?php

use kartik\select2\Select2;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;


/* @var $this yii\web\View */
/* @var $model common\models\ProgramStudi */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $dataFakultas \common\models\FakultasAkademi[] */
?>


<div class="program-studi-form">

    <?php $form = ActiveForm::begin(['enableClientScript' => true, 'id' => 'prodi-form']); ?>

    <?= $form->field($model, 'kode')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'kaprodi')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'jurusan_departemen')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'jenjang')->widget(Select2::class,[
        'data'=>\common\models\ProgramStudi::JENJANG,
        'options' => ['class'=>'kt-select2','placeholder'=>'Pilih Jenjang'],
    ])->label('Jenjang') ?>

    <?= $form->field($model, 'id_fakultas_akademi')->widget(Select2::class,[
        'data'=>$dataFakultas,
        'options' => ['class'=>'kt-select2','placeholder'=>'Pilih Fakultas'],
    ])->label('Fakultas/Akademi') ?>

    <?= $form->field($model, 'nomor_sk_pendirian')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'tanggal_sk_pendirian')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'pejabat_ttd_sk_pendirian')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'bulan_berdiri')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'tahun_berdiri')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'nomor_sk_operasional')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'tanggal_sk_operasional')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'peringkat_banpt_terakhir')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'nilai_banpt_terakhir')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'nomor_sk_banpt')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'alamat')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'kodepos')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'nomor_telp')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'homepage')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('<i class=\'la la-save\'></i> Simpan', ['class' => 'btn btn-pill btn-elevate btn-elevate-air btn-brand block-ui']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<?php
$jsForm = <<<JS
 $('form').on('beforeSubmit', function()
    {
        var form = $(this);
        //console.log('before submit');

        var submit = form.find(':submit');
        KTApp.block('.modal',{
            overlayColor: '#000000',
            type: 'v2',
            state: 'primary',
            message: 'Sedang Memproses...'
        });
        submit.html('<i class="flaticon2-refresh"></i> Sedang Memproses');
        submit.prop('disabled', true);
        
    });

JS;

$this->registerJs($jsForm);
?>

akreditasi/modules/kriteria9/modules/prodi/views/profil/index.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $programstudi common\models\ProgramStudi */
/**
 * @var $model common\models\Profil
 */

$this->title = 'Profil: ' . $programstudi->nama;
$this->params['breadcrumbs'][] = ['label' => 'Program Studi', 'url' => ['/kriteria9/prodi/arsip']];
$this->params['breadcrumbs'][] = ['label' => $programstudi->nama, 'url' => ['default/index', 'prodi' => $programstudi->id]];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="flaticon2-edit"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        <?= Html::encode($this->title) ?>
                    </h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">

                            <?= Html::a('<i class=flaticon2-edit></i> Edit Prodi', ['profil/update', 'prodi' => Yii::$app->request->get('prodi')], ['class' => 'btn btn-info btn-elevate btn-elevate-air']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="program-studi-prodi">
                    <?=\yii\widgets\DetailView::widget([
                        'model' => $programstudi,
                            'attributes' => [
                                'id',
                                'kode',
                                'nama',
                                'jurusan_departemen',
                                'fakultasAkademi.nama',
                                'nomor_sk_pendirian',
                                'tanggal_sk_pendirian',
                                'pejabat_ttd_sk_pendirian',
                                'bulan_berdiri',
                                'tahun_berdiri',
                                'nomor_sk_operasional',
                                'tanggal_sk_operasional',
                                'peringkat_banpt_terakhir',
                                'nilai_banpt_terakhir',
                                'nomor_sk_banpt',
                                'alamat',
                                'kodepos',
                                'nomor_telp',
                                'homepage',
                                'email:email',
                                'kaprodi',
                                'jenjang',
                                'created_at:datetime',
                                'updated_at:datetime',
                            ],
                        ]
                    )?>


                </div>
            </div>
        </div>
        <!--end::Portlet-->

    </div>
</div>

<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="flaticon2-edit"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        <?= Html::encode($this->title) ?>
                    </h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">

                            <?= Html::a('<i class=flaticon2-edit></i> Edit Profil Prodi', ['profil/update-profil', 'prodi' => Yii::$app->request->get('prodi')], ['class' => 'btn btn-info btn-elevate btn-elevate-air']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="program-studi-prodi">
                    <?=\yii\widgets\DetailView::widget([
                            'model' => $programstudi->profil,
                            'attributes' => [
//                                'id',
                                'visi:html',
                                'misi:html',
                                'tujuan:html',
                                'sasaran:html',
                                'motto:html',
                                'sambutan:html',
                                ['attribute'=>'struktur_organisasi',
                                    'format'=>['image',['width'=>'50%']],
                                    'value'=>function($model){
                        return Yii::getAlias("@.uploadStruktur/{$model->type}/{$model->external_id}/$model->struktur_organisasi");
                                    }]
                            ],
                        ]
                    )?>


                </div>
            </div>
        </div>
        <!--end::Portlet-->

    </div>
</div>

akreditasi/modules/kriteria9/modules/prodi/views/profil/update-profil.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ProgramStudi */
/* @var $profil common\models\Profil */
/* @var $strukturModel akreditasi\models\StrukturOrganisasiUploadForm */

$this->title = 'Update Profil Program Studi: ' . $model->nama;
$this->params['breadcrumbs'][] = ['label' => 'Program Studi', 'url' => ['/kriteria9/prodi/arsip']];
$this->params['breadcrumbs'][] = ['label' => $model->nama, 'url' => ['default/index', 'prodi' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="flaticon2-edit"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        <?= Html::encode($this->title) ?>
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="program-studi-update">

                    <?= $this->render('_form-profil', [
                    'model' => $model,
                        'profil'=>$profil,
                        'strukturModel'=>$strukturModel

                    ]) ?>

                </div>
            </div>
        </div>
        <!--end::Portlet-->

    </div>
</div>

akreditasi/modules/kriteria9/modules/prodi/views/profil/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ProgramStudi */
/* @var $dataFakultas common\models\FakultasAkademi[] */
/* @var $jenjang array */

$this->title = 'Update Program Studi: ' . $model->nama;
$this->params['breadcrumbs'][] = ['label' => 'Program Studi', 'url' => ['/kriteria9/prodi/arsip']];
$this->params['breadcrumbs'][] = ['label' => $model->nama, 'url' => ['default/index', 'prodi' => $model->id]];
$this->params['breadcrumbs'][] = 'Ubah';
?>

<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="flaticon2-edit"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        <?= Html::encode($this->title) ?>
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="program-studi-update">

                    <?= $this->render('@admin/views/program-studi/_form', [
                    'model' => $model,
                        'dataFakultas'=>$dataFakultas,
                        'jenjang'=>$jenjang

                    ]) ?>

                </div>
            </div>
        </div>
        <!--end::Portlet-->

    </div>
</div>