akreditasi/modules/kriteria9/modules/prodi/controllers/LedController.php
<?php
/**
 * Project: mutu-v2.
 * @author Adryan Eka Vandra <adryanekavandra@gmail.com>
 *
 * Date: 9/7/2019
 * Time: 12:36 AM
 */

namespace akreditasi\modules\kriteria9\modules\prodi\controllers;


use akreditasi\models\kriteria9\forms\led\K9DetailLedProdiLinkForm;
use akreditasi\models\kriteria9\forms\led\K9DetailLedProdiTeksForm;
use akreditasi\models\kriteria9\forms\led\K9DetailLedProdiUploadForm;
use akreditasi\models\kriteria9\forms\led\K9DokumenLedProdiUploadForm;
use akreditasi\modules\kriteria9\controllers\BaseController;
use common\helpers\kriteria9\K9ProdiDirectoryHelper;
use common\models\Constants;
use common\models\kriteria9\akreditasi\K9Akreditasi;
use common\models\kriteria9\forms\led\K9PencarianLedProdiForm;
use common\models\kriteria9\led\prodi\K9DokumenLedProdi;
use common\models\kriteria9\led\prodi\K9LedProdi;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria1;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria2;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria3;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria4;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria5;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria6;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria7;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria8;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria9;
use common\models\ProgramStudi;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\MethodNotAllowedHttpException;
use yii\web\UploadedFile;

class LedController extends BaseController
{

    public function actionArsip($target, $prodi)
    {

        $model = new K9PencarianLedProdiForm();
        $akreditasi = K9Akreditasi::findAll(['jenis_akreditasi' => Constants::PRODI]);
        $progdi = ProgramStudi::findAll(['id' => $prodi]);
        $dataProdi = ArrayHelper::map($progdi, 'id', 'nama');
        $dataAkreditasi = ArrayHelper::map($akreditasi, 'id', function ($data) {
            return $data->nama . " (" . $data->tahun . ")";
        });

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                $url = $model->cari($target);
                $led = $model->getLed();
                $newUrl = [];
                if (!$led) $newUrl = false;
                else $newUrl = $url;

                return $this->renderAjax('_hasil-arsip', ['led' => $led, 'url' => $newUrl]);

            }
        }
        return $this->render('arsip', [
            'model' => $model,
            'dataAkreditasi' => $dataAkreditasi,
            'dataProdi' => $dataProdi
        ]);

    }

    public function actionIsi($led, $prodi)
    {
        $ledProdi = K9LedProdi::findOne($led);

        $modelDokumen = new K9DokumenLedProdiUploadForm();
        $dataDokumen = K9DokumenLedProdi::findAll(['id_led_prodi' => $led]);
        $json = $this->getJsonData();
        $kriteria = $this->getArrayKriteria($led);
        $realPath = K9ProdiDirectoryHelper::getDokumenLedUrl($ledProdi->akreditasiProdi);

        if ($modelDokumen->load(Yii::$app->request->post())) {

            $dokumen = $this->uploadDokumenLed($led);
            if ($dokumen) {
                $model = new K9DokumenLedProdi();
                $model->id_led_prodi = $ledProdi->id;
                $model->nama_dokumen = $dokumen->getNamaDokumen();
                $model->bentuk_dokumen = $dokumen->getBentukDokumen();
                $model->save(false);

                Yii::$app->session->setFlash('success', 'Berhasil mengunggah Dokumen LED');
                return $this->redirect(Url::current());
            }
            Yii::$app->session->setFlash('warning', 'Gagal mengunggah Dokumen LED');
            return $this->redirect(Url::current());
        }

        return $this->render('led', [
            'led' => $ledProdi,
            'modelDokumen' => $modelDokumen,
            'dataDokumen' => $dataDokumen,
            'json' => $json,
            'kriteria' => $kriteria,
            'path' => $realPath
        ]);
    }

    protected function getJsonData()
    {
        $fileJson = 'led_prodi.json';
        $json = Json::decode(file_get_contents(Yii::getAlias('@common/required/kriteria9/aps/' . $fileJson)));
        return $json;

    }

    protected function getArrayKriteria($led)
    {
        $kriteria1 = K9LedProdiKriteria1::findOne(['id_led_prodi' => $led]);
        $kriteria2 = K9LedProdiKriteria2::findOne(['id_led_prodi' => $led]);
        $kriteria3 = K9LedProdiKriteria3::findOne(['id_led_prodi' => $led]);
        $kriteria4 = K9LedProdiKriteria4::findOne(['id_led_prodi' => $led]);
        $kriteria5 = K9LedProdiKriteria5::findOne(['id_led_prodi' => $led]);
        $kriteria6 = K9LedProdiKriteria6::findOne(['id_led_prodi' => $led]);
        $kriteria7 = K9LedProdiKriteria7::findOne(['id_led_prodi' => $led]);
        $kriteria8 = K9LedProdiKriteria8::findOne(['id_led_prodi' => $led]);
        $kriteria9 = K9LedProdiKriteria9::findOne(['id_led_prodi' => $led]);

        $kriteria = [$kriteria1, $kriteria2, $kriteria3, $kriteria4, $kriteria5, $kriteria6, $kriteria7, $kriteria8, $kriteria9];

        return $kriteria;
    }

    protected function uploadDokumenLed($led)
    {
        $ledProdi = K9LedProdi::findOne($led);

        $dokumenLed = new K9DokumenLedProdiUploadForm();
        $dokumenLed->dokumenLed = UploadedFile::getInstance($dokumenLed, 'dokumenLed');
        $realPath = K9ProdiDirectoryHelper::getDokumenLedPath($ledProdi->akreditasiProdi);
        $response = null;

        if ($dokumenLed->validate()) {

            $uploaded = $dokumenLed->uploadDokumen($realPath);
            if ($uploaded) {
                $response = $dokumenLed;
            }

        }

        return $response;


    }

    public function actionHapusDokumenLed()
    {
        if (Yii::$app->request->isPost) {

            $data = Yii::$app->request->post();

            $idDokumenLed = $data['id'];
            $prodi = $data['prodi'];
            $dokumenLedProdi = K9DokumenLedProdi::findOne($idDokumenLed);
            $path = K9ProdiDirectoryHelper::getDokumenLedPath($dokumenLedProdi->ledProdi->akreditasiProdi);
            $deleteDokumen = FileHelper::unlink($path . "/" . $dokumenLedProdi->nama_dokumen);
            if ($deleteDokumen) {
                $dokumenLedProdi->delete();
                Yii::$app->session->setFlash('success', 'Berhasil menghapus dokumen led');
                return $this->redirect(['led/isi', 'led' => $dokumenLedProdi->ledProdi->id, 'prodi' => $prodi]);

            }
            Yii::$app->session->setFlash('success', 'Gagal menghapus dokumen led');
            return $this->redirect(['led/isi', 'led' => $dokumenLedProdi->ledProdi->id, 'prodi' => $prodi]);

        }

        return new MethodNotAllowedHttpException('Harus melalui prosedur penghapusan data.');

    }

    public function actionDownloadDokumen($dokumen)
    {
        ini_set('max_execution_time', 5 * 60);
        $model = K9DokumenLedProdi::findOne($dokumen);
        $file = K9ProdiDirectoryHelper::getDokumenLedPath($model->ledProdi->akreditasiProdi) . "/{$model->nama_dokumen}";
        return Yii::$app->response->sendFile($file);
    }

    public function actionIsiKriteria($led, $kriteria, $prodi)
    {

        $modelLedClass = 'common\\models\\kriteria9\\led\\prodi\\K9LedProdiKriteria' . $kriteria;
        $modelLed = call_user_func($modelLedClass . '::findOne', $led);

        $modelNarasiClass = 'akreditasi\\models\\kriteria9\\led\\prodi\\K9LedProdiNarasiKriteria' . $kriteria . 'Form';
        $modelNarasi = call_user_func($modelNarasiClass . '::findOne', ['id_led_prodi_kriteria' . $kriteria => $modelLed->id]);

        $json = $this->getJsonData();
        $dataKriteria = $json[$kriteria - 1];
        $poinKriteria = $dataKriteria['butir'];


        $detailModel = new K9DetailLedProdiUploadForm();
        $textModel = new K9DetailLedProdiTeksForm();
        $linkModel = new K9DetailLedProdiLinkForm();


        $realPath = K9ProdiDirectoryHelper::getDetailLedUrl($modelLed->ledProdi->akreditasiProdi);


        if ($modelNarasi->load(Yii::$app->request->post())) {
            $modelNarasi->save();
            Yii::$app->session->setFlash('success', 'Berhasil Memperbarui Entri');
            return $this->redirect(Url::current());

        }
        if ($detailModel->load(Yii::$app->request->post())) {
            $detailModel->berkasDokumen = UploadedFile::getInstance($detailModel, 'berkasDokumen');

            if ($detailModel->uploadDokumen($modelLed->id, $kriteria)) {
                Yii::$app->session->setFlash('success', 'Berhasil Mengunggah Dokumen');
                return $this->redirect(Url::current());

            }

            Yii::$app->session->setFlash('warning', 'Gagal menunggah Dokumen');
            return $this->redirect(Url::current());

        }
        if ($textModel->load(Yii::$app->request->post())) {
            if ($textModel->save($led, $kriteria)) {
                Yii::$app->session->setFlash('success', 'Berhasil Menambahkan dokumen');
                return $this->redirect(Url::current());
            }
            Yii::$app->session->setFlash('warning', 'Gagal Menambahkan Dokumen');
            return $this->redirect(Url::current());

        }

        if ($linkModel->load(Yii::$app->request->post())) {
            if ($linkModel->save($led, $kriteria)) {
                Yii::$app->session->setFlash('success', 'Berhasil Menambahkan dokumen');
                return $this->redirect(Url::current());
            }
            Yii::$app->session->setFlash('warning', 'Gagal Menambahkan Dokumen');
            return $this->redirect(Url::current());

        }


        return $this->render('isi-kriteria', [
            'model' => $modelLed,
            'modelNarasi' => $modelNarasi,
            'poinKriteria' => $poinKriteria,

akreditasi/modules/kriteria9/modules/prodi/views/led/_hasil-arsip.php
<?php
/**
 * Project: mutu-v2.
 * @author Adryan Eka Vandra <adryanekavandra@gmail.com>
 *
 * Date: 8/26/2019
 * Time: 11:36 AM
 */

/**
 * @var $led K9LedProdi
 * @var $url array
 */

use common\models\kriteria9\led\prodi\K9LedProdi;
use yii\bootstrap4\Html;

?>

<div class="kt-portlet">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
                Hasil Pencarian
                <h3>
        </div>
    </div>
    <div class="kt-portlet__body">
        <div class="kt-section kt-section--first" style="margin-bottom: 0;">

            <?php if (!$led) : echo "Tidak ada Data"; else: ?>
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th>No</th>
                        <th>Nama Akreditasi</th>
                        <th>Tahun</th>
                        <th>Lembaga</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <td>1</td>
                        <td><?= $led->akreditasiProdi->akreditasi->nama ?></td>
                        <td><?= $led->akreditasiProdi->akreditasi->tahun ?></td>
                        <td><?= $led->akreditasiProdi->akreditasi->lembaga ?></td>
                        <td><?= Html::a('<i class="la la-folder"></i> Lihat', $url, ['class' => ['btn btn-default btn-pill btn-elevate btn-elevate-air']]) ?></td>
                    </tr>

                    </tbody>
                </table>

            <?php endif; ?>

        </div>
    </div>

    <!--end::Form-->
</div>

akreditasi/modules/kriteria9/modules/prodi/views/led/arsip.php
<?php
/**
 * @var $this yii\web\View
 * @var $model K9PencarianLedProdiForm
 * @var $dataAkreditasi array
 * @var $dataProdi array
 */
$this->title = "Pencarian LED";

$this->params['breadcrumbs'][] = ['label' => 'Beranda', 'url' => ['/site/index']];

$this->params['breadcrumbs'][] = ['label' => '9 Kriteria', 'url' => ['/kriteria9/default/index']];
$this->params['breadcrumbs'][] = ['label' => 'Program Studi', 'url' => ['/kriteria9/k9-prodi/default/index']];
$this->params['breadcrumbs'][] = $this->title;


use common\models\kriteria9\forms\led\K9PencarianLedProdiForm;
use demogorgorn\ajax\AjaxSubmitButton;
use kartik\select2\Select2;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\web\JsExpression;
use yii\widgets\Pjax;

?>
<!--card-->

<div class="kt-portlet">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
                Form Pencarian borang
            </h3>
        </div>
    </div>

    <!--begin::Form-->
    <?php $form = ActiveForm::begin(['id' => 'form-pencarian-led', 'options' => ['class' => 'kt-form']]) ?>
    <div class="kt-portlet__body">
        <div class="kt-section kt-section--first" style="margin-bottom: 0;">

            <?= $form->field($model, 'akreditasi')->widget(Select2::class, [
                'data' => $dataAkreditasi,
                'pluginOptions' => ['placeholder' => 'Pilih Akreditasi'],

            ]) ?>
            <?= $form->field($model, 'prodi')->widget(Select2::class, [
                'data' => $dataProdi,
            ]) ?>

        </div>
    </div>
    <div class="kt-portlet__foot">
        <div class="kt-form__actions">
            <?php AjaxSubmitButton::begin([
                'label' => 'Cari',
                'icon' => 'la la-search',
                'useWithActiveForm' => 'form-pencarian-led',
                'ajaxOptions' => [
                    'type' => 'POST',
                    'success' => new JsExpression('function(html){
                        $("#hasil-arsip").html(html);
                        normalizeButton("submit-form");
                    }')

                ],
                'options' => ['class' => 'btn btn-success btn-pill btn-elevate btn-elevate-air', 'type' => 'submit', 'id' => 'submit-form']
            ]);

            AjaxSubmitButton::end();

            ?>


        </div>
    </div>
    <?php ActiveForm::end() ?>

    <!--end::Form-->
</div>

<div id="hasil-arsip"></div>

akreditasi/modules/kriteria9/modules/prodi/views/led/led.php
<?php
/**
 * Project: mutu-v2.
 * @author Adryan Eka Vandra <adryanekavandra@gmail.com>
 *
 * Date: 8/26/2019
 * Time: 1:54 PM
 */
/**
 * @var $this View
 * @var $led K9LedProdi
 * @var $modelDokumen K9DokumenLedProdiUploadForm;
 * @var $dataDokumen [];
 * @var $json array;
 * @var $kriteria [];
 */
$prodi = $_GET['prodi'];

$this->title = "Isi LED";
$this->params['breadcrumbs'][] = ['label' => 'Beranda', 'url' => ['/site/index']];
$this->params['breadcrumbs'][] = ['label' => '9 Kriteria', 'url' => ['/kriteria9/default/index']];
$this->params['breadcrumbs'][] = ['label' => 'Prodi', 'url' => ['/kriteria9/k9-prodi/default/index']];
$this->params['breadcrumbs'][] = ['label' => 'Led', 'url' => ['/kriteria9/k9-prodi/led/arsip', 'target' => 'isi','prodi'=>$prodi]];
$this->params['breadcrumbs'][] = $this->title;

use akreditasi\models\kriteria9\forms\led\K9DokumenLedProdiUploadForm;
use common\helpers\FileIconHelper;
use common\helpers\FileTypeHelper;
use common\models\Constants;
use common\models\kriteria9\led\prodi\K9LedProdi;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria1;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria2;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria3;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria4;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria5;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria6;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria7;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria8;
use common\models\kriteria9\led\prodi\K9LedProdiKriteria9;
use common\models\kriteria9\led\prodi\K9DokumenLedProdi;
use kartik\file\FileInput;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\bootstrap4\Modal;
use yii\bootstrap4\Progress;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use yii\web\View;

?>


<div class="kt-portlet">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
                Form
                LED <?= Html::encode(StringHelper::mb_ucfirst($led->akreditasiProdi->akreditasi->jenis_akreditasi)) ?>
            </h3>
        </div>
    </div>

    <div class="kt-portlet__body">
        <div class="kt-section kt-section--first" style="margin-bottom: 0;">

            <table class="table table-striped">

                <tbody>
                <tr>
                    <th scope="row">Laporan Evaluasi Diri</th>
                    <td>Akreditasi Program Studi</td>
                </tr>
                <tr>
                    <th scope="row">Lembaga Akreditasi</th>
                    <td><?= Html::encode($led->akreditasiProdi->akreditasi->lembaga) ?></td>
                </tr>
                <tr>
                    <th scope="row">Tahun Akreditasi</th>
                    <td><?= Html::encode($led->akreditasiProdi->akreditasi->tahun) ?></td>
                </tr>
                <tr>
                    <th scope="row">Jenis Akreditasi</th>
                    <td><?= Html::encode(StringHelper::mb_ucfirst($led->akreditasiProdi->akreditasi->jenis_akreditasi)) ?></td>
                </tr>
                <tr>
                    <th scope="row">LED Untuk</th>
                    <td>Program Studi</td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>

<div class="kt-portlet">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
                Dokumen LED
                <small>Silahkan unggah dokumen led yang telah disusun.</small>
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-actions">
                <?php Modal::begin([
                    'title' => 'Unggah Dokumen Led',
                    'toggleButton' => ['label' => '<i class="la la-upload"></i> &nbsp;Unggah', 'class' => 'btn btn-primary btn-pill btn-elevate btn-elevate-air'],
                    'size' => 'modal-lg',
                    'clientOptions' => ['backdrop' => 'blur', 'keyboard' => true]
                ]); ?>

                <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data'],'id'=>'dokumen-led-form']) ?>

                <?= $form->field($modelDokumen, 'dokumenLed')->widget(FileInput::class, [
                    'pluginOptions' => [
                        'theme' => 'explorer-fas',
                        'maxFileSize' => Constants::MAX_UPLOAD_SIZE(),
                        'allowedFileExtensions' => Constants::ALLOWED_EXTENSIONS,
                        'showUpload' => false,
                        'previewFileType' => 'any',
                        'fileActionSettings' => [
                            'showZoom' => true,
                            'showRemove' => false,
                            'showUpload' => false,
                        ],
                    ]
                ]) ?>

                <div class="form-group pull-right">
                    <?= Html::submitButton('<i class="la la-save"></i> Simpan', ['class' => 'btn btn-primary btn-pill btn-elevate btn-elevate-air']) ?>
                </div>
                <?php ActiveForm::end() ?>

                <?php Modal::end(); ?>
            </div>
        </div>

    </div>

    <div class="kt-portlet__body">
        <div class="kt-section kt-section--first" style="margin-bottom: 0;">
            <table class="table table-hover table-light table-striped">
                <thead class="thead-light">
                <tr>

                    <th>No.</th>
                    <th>Dokumen Led</th>
                    <th>
                        Aksi
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($dataDokumen as $key => $item) : ?>
                    <tr>
                        <td><?= $key + 1 ?></td>
                        <td>
                            <div class="row">
                                <div class="col-lg-12 text-center">
                                    <?= FileIconHelper::getIconByExtension($item->bentuk_dokumen) ?>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-lg-12 text-center">
                                    <?= Html::encode($item->nama_dokumen) ?>

                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="row pull-right">
                                <div class="col-lg-12">
                                    <?php $type = FileTypeHelper::getType($item->bentuk_dokumen);
                                    if ($type === FileTypeHelper::TYPE_IMAGE || $type === FileTypeHelper::TYPE_PDF):?>
                                        <?php Modal::begin([
                                            'title' => $item->nama_dokumen,
                                            'toggleButton' => ['label' => '<i class="la la-eye"></i> &nbsp;Lihat', 'class' => 'btn btn-info btn-pill btn-elevate btn-elevate-air'],
                                            'size' => 'modal-lg',
                                            'clientOptions' => ['backdrop' => 'blur', 'keyboard' => true]
                                        ]); ?>
                                        <?php switch ($type) {
                                            case FileTypeHelper::TYPE_IMAGE:
                                                echo Html::img("$path/{$item->nama_dokumen}", ['height' => '100%', 'width' => '100%']);
                                                break;
                                            case FileTypeHelper::TYPE_PDF:
                                                echo '<embed src="' . $path . '/' . $item->nama_dokumen . '" type="application/pdf" height="100%" width="100%">
';
                                                break;
                                        } ?>
                                        <?php Modal::end(); ?>
                                    <?php endif; ?>
                                    <?= Html::a('<i class ="la la-download"></i> Unduh', ['led/download-dokumen', 'dokumen' => $item->id], ['class' => 'btn btn-warning btn-pill btn-elevate btn-elevate-air']) ?>
                                    <?= Html::a('<i class ="la la-trash"></i> Hapus', ['led/hapus-dokumen-led'], ['class' => 'btn btn-danger btn-pill btn-elevate btn-elevate-air', 'data' => [
                                        'method' => 'POST',
                                        'confirm' => 'Apakah anda yakin menghapus item ini?',
                                        'params' => ['id' => $item->id,'prodi'=>$prodi]
                                    ]]) ?>
                                </div>

                            </div>


                        </td>
                    </tr>

                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="kt-portlet">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
                Isi Led
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-actions">
                <strong>Kelengkapan Berkas:&nbsp;<?= Html::encode($led->progress) ?> %</strong>
                <div class="kt-space-10"></div>
                <?=
                Progress::widget([
                    'percent' => $led->progress,
                    'barOptions' => ['class' => 'progress-bar-info m-progress-lg'],
                    'options' => ['class' => 'progress-sm']
                ]); ?>
            </div>
        </div>
    </div>

    <div class="kt-portlet__body">
        <div class="kt-section kt-section--first" style="margin-bottom: 0;">

            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th>No.</th>
                    <th>Kriteria Akreditasi</th>
                    <th style="width: 110px"></th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($json as $kriteriaJson): ?>
                    <tr>
                        <th scope="row"><?= Html::encode($kriteriaJson['kriteria']) ?></th>
                        <td>
                            <strong>Kriteria <?= Html::encode($kriteriaJson['kriteria']) ?>
                                : <?= $kriteria[$kriteriaJson['kriteria'] - 1]->progress ?>%</strong><br>
                            <?= $kriteriaJson['judul'] ?>
                            <div class="kt-space-10"></div>
                            <?=
                            Progress::widget([
                                'percent' => $kriteria[$kriteriaJson['kriteria'] - 1]->progress,
                                'barOptions' => ['class' => 'progress-bar-info m-progress-lg'],
                                'options' => ['class' => 'progress-sm']
                            ]); ?>
                        </td>
                        <td style="padding-top: 15px;">
                            <?= Html::a("<i class='la la-folder-open'></i>Lihat", ['led/isi-kriteria', 'led' => $_GET['led'], 'kriteria' => $kriteriaJson['kriteria'],'prodi'=>$prodi], ['class' => 'btn btn-default btn-pill btn-elevate btn-elevate-air']) ?>

                            <!--                        <button type="button" class="btn btn-danger">Lihat</button>-->
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>